name: liferay-mysql
services:
  mysql:
    image: mysql:8.0-oracle
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: lportal
      MYSQL_USER: liferay
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./volumes/mysql/data:/var/lib/mysql
      - ./volumes/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - default
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "liferay", "-ptest"]
      interval: 10s
      timeout: 5s
      retries: 5

  liferay:
    image: liferay/portal:7.4.3.129-ga129
    container_name: mysql-liferay-portal
    ports:
      - "18080:8080"
      - "8010:8010"
      - "8443:8443"
      - "11311:11311"
    environment:
      LIFERAY_JDPA_ENABLED: "true"
      JPDA_ADDRESS: "8000"
      JPDA_TRANSPORT: dt_socket
      LIFERAY_RETRY_PERIOD_JDBC_PERIOD_ON_PERIOD_STARTUP_PERIOD_DELAY: 10
      LIFERAY_RETRY_PERIOD_JDBC_PERIOD_ON_PERIOD_STARTUP_PERIOD_MAX_PERIOD_RETRIES: 10
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./volumes/liferay/deploy:/opt/liferay/deploy
      - ./volumes/liferay/data:/opt/liferay/data
      - ./volumes/liferay/portal-ext.properties:/opt/liferay/portal-ext.properties
      - ./volumes/liferay/osgi/modules:/opt/liferay/osgi/modules
      - ./volumes/liferay/osgi/war:/opt/liferay/osgi/war
    networks:
      - default

networks:
  default:
    driver: bridge
